workflows:
  build-android:
    name: Build Android APK
    max_build_duration: 15
    environment:
      flutter: stable
      vars:
        BUILD_NAME: "1.0.0"
        BUILD_NUMBER: "1"
        KEYSTORE_PATH: "android/app/my-release-key.jks"
        KEYSTORE_PASSWORD: Hasnain123
        KEY_ALIAS: my-key-alias
        KEY_PASSWORD: Hasnain123
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
